nginx:
  build: _docker/nginx
  environment:
    VIRTUAL_HOST: wp-test-demo
  links:
    - php
  ports:
    - "8080:80"
  volumes:
    - .:/app

php:
  build: _docker/php
  links:
    - db
    - es
    - redis
    - fakes3ssl:testbucket.s3.amazonaws.com
  volumes:
    - .:/app
  working_dir: /app
  user: "1000"

db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: dk8e_z-e5e

es:
  image: elasticsearch

redis:
  image: redis

fakes3:
  image: lphoward/fake-s3
  ports:
    - "4569:4569"

fakes3ssl:
  image: cbachich/ssl-proxy
  ports:
    - "443:443"
  links:
    - fakes3:proxyapp
  environment:
    - PORT=443
    - TARGET_PORT=4569
